name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Xcode Selection
      run: sudo xcode-select -s /Applications/Xcode_11.1.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
